"""Identifiers and idempotency keys.

Two distinct concepts, deliberately kept apart:

* **Resource identifiers** are generated by the system, are UUIDs, and carry no meaning.
  This system does not use sequential IDs for user-visible resources, because sequential IDs
  leak cardinality and invite enumeration.

* **Idempotency keys** are supplied by the *client*, must be stable across retries of the *same*
  intent, and are validated rather than generated. Generating them would defeat the purpose:
  a retry cannot know what the server issued the first time.

Conflating them is a common bug: it produces a system that is idempotent only for the first
attempt.
"""

from __future__ import annotations

import re
import uuid

from knowledge_assistant.domain.errors import ValidationError

__all__ = [
    "IDEMPOTENCY_KEY_MIN_LENGTH",
    "IDEMPOTENCY_KEY_MAX_LENGTH",
    "IDEMPOTENCY_KEY_PATTERN",
    "new_id",
    "new_request_id",
    "validate_idempotency_key",
    "is_valid_idempotency_key",
]

#: Minimum length: long enough that an accidental short value (a counter, a timestamp) is
#: unlikely to be accepted as an intent token.
IDEMPOTENCY_KEY_MIN_LENGTH: int = 16

#: Maximum length: bounds storage per key and bounds the work of validating one.
IDEMPOTENCY_KEY_MAX_LENGTH: int = 255

#: Permitted characters: URL-safe base64 alphabet plus the separator. Deliberately narrow:
#: keys travel in HTTP headers, and header-legal but path-unsafe characters create bugs when
#: a key is ever echoed into a URL or a log line.
IDEMPOTENCY_KEY_PATTERN: re.Pattern[str] = re.compile(r"^[A-Za-z0-9._~-]{16,255}$")

#: Namespace for UUID generation. UUID4 is random; a UUID7 implementation (time-ordered) is
#: a considered upgrade for index locality, deferred until the write-amplification question
#: is measured rather than assumed. See docs/03-architecture/PGVECTOR_HYPOTHESIS.md.
_UUID_NAMESPACE = uuid.UUID("6f9c2f1e-5a3b-4d7e-9f10-2b8c4d6e0a11")


def new_id() -> uuid.UUID:
    """Return a new random (UUID4) resource identifier.

    Returns:
        A fresh UUID. Not derived from time or state, so identifiers leak neither volume nor
        ordering.
    """
    return uuid.uuid4()


def new_request_id() -> str:
    """Return a new request-correlation identifier in canonical UUID text form.

    Returns:
        36-character hyphenated UUID string, suitable for an HTTP header and a log field.
    """
    return str(uuid.uuid4())


def is_valid_idempotency_key(value: str) -> bool:
    """Return whether ``value`` is a well-formed idempotency key.

    Args:
        value: Candidate key.

    Returns:
        ``True`` if the key satisfies the length bounds and character allow-list.
    """
    return IDEMPOTENCY_KEY_PATTERN.fullmatch(value) is not None


def validate_idempotency_key(value: str) -> str:
    """Validate and normalise an idempotency key.

    Args:
        value: Candidate key from the request.

    Returns:
        The key, unchanged. Normalisation is deliberately the identity function: any
        case-folding or trimming would risk merging two distinct client intents, and a
        merged idempotency namespace returns the wrong cached response. Validation must
        not mutate meaning.

    Raises:
        ValidationError: If the key is not well-formed. The message names the field but
            echoes no part of the supplied value, so a malformed key cannot inject content
            into logs.
    """
    if not is_valid_idempotency_key(value):
        msg = (
            f"idempotency key must be {IDEMPOTENCY_KEY_MIN_LENGTH}-{IDEMPOTENCY_KEY_MAX_LENGTH} "
            f"characters of [A-Za-z0-9._~-]"
        )
        raise ValidationError(msg, detail={"field": "idempotency_key"})
    return value


def namespaced_uuid(name: str) -> uuid.UUID:
    """Return a stable UUIDv5 derived from ``name`` and this system's namespace.

    Used only for idempotency scope keys and test fixtures, never for user-visible resource
    identity, so that determinism is useful here and dangerous elsewhere.

    Args:
        name: Stable, human-meaningful name.

    Returns:
        Deterministic UUID for ``(namespace, name)``.
    """
    return uuid.uuid5(_UUID_NAMESPACE, name)